name: papucon
description: Papucon Messenger

version: 1.1.4 #출시명 변경

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  path_provider: ^1.6.11
  downloads_path_provider:
    path: "downloads_path_provider"
  image_downloader: ^0.20.0
  flutter:
    sdk: flutter
  fluttericon: ^1.0.7
  fluid_bottom_nav_bar: ^1.0.1
  progress_dialog: ^1.2.4
  numeric_keyboard: ^1.0.0
  firebase_core: ^0.4.4
  cloud_firestore: ^0.13.7
  multi_query_firestore: ^1.0.0+2
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.15.5+3
  firebase_storage: ^3.0.6
  cached_network_image: 2.0.0-rc.1
  firebase_messaging: ^6.0.9
  flutter_local_notifications: ^1.4.4+2
  photo_view: ^0.5.0
  webview_flutter: ^0.3.22+1
  rflutter_alert: ^1.0.3
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  provider: ^4.0.4
  translator: ^0.1.5
  cupertino_icons: ^0.1.3
  file_picker: ^1.12.0
  material_design_icons_flutter: ^4.0.5345
  flutter_statusbarcolor: ^0.2.3
  http: ^0.12.2
  http2: ^1.0.0
  uuid: ^2.2.2
  image_picker: ^0.6.7+8
  shared_preferences: ^0.5.3+4
  flutter_masked_text: ^0.8.0
  get_it: ^4.0.4
  agora_rtc_engine: 1.0.5
  flutter_ios_voip_kit: ^0.0.4+1
  permission_handler: ^3.0.0
  popup_menu: ^1.0.5
  fluttertoast: ^3.1.3
  random_string: ^2.0.1
  flutter_svg: ^0.18.0
  flutter_launcher_icons: "^0.7.5"
  localstorage: ^3.0.0
  sqflite: ^1.1.6
  path: ^1.6.2
  carousel_slider: ^2.2.1
  rxdart: ^0.24.1
  percent_indicator: ^2.1.5
  flutter_downloader: ^1.4.4
  assets_audio_player: ^2.0.9+2
  multi_image_picker: ^4.6.7
  flutter_neumorphic: ^3.0.1
  #background_fetch: ^0.6.0
  easy_localization: ^2.3.2
  flutter_gifimage: ^1.0.0
  in_app_update: ^1.1.11
  image_gallery_saver: '^1.5.0'
  open_file: ^3.0.1
  #bubble_bottom_bar: ^1.2.0
  image_gallery:
    path: "image_gallery"
  #workmanager: ^0.2.3
  #system_alert_window: ^0.3.2+2
  get:
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  mobx_codegen: ^1.0.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/CustomIcons.ttf
    - assets/img/
    - assets/guideImages/
    - assets/img/noface.png
    - assets/translations/
    - assets/sound/papupapu.mp3
    - assets/sound/bensound-anewbeginning.mp3
    - assets/images/img_not_available.jpeg
    - assets/icon/ic_launcher.png
    - assets/images/mimi1.gif
    - assets/images/mimi2.gif
    - assets/images/mimi3.gif
    - assets/images/mimi4.gif
    - assets/images/mimi5.gif
    - assets/images/mimi6.gif
    - assets/images/Picon01.gif
    - assets/images/Picon02.gif
    - assets/images/Picon03.gif
    - assets/images/Picon04.gif
    - assets/images/Picon05.gif
    - assets/images/Picon06.gif
    - assets/images/Picon07.gif
    - assets/images/Picon08.gif
    - assets/images/Picon09.gif
    - assets/images/Picon10.gif
    - assets/images/Picon11.gif
    - assets/images/Picon12.gif
